# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc6c5ae77534484b249f685e9afe5ca319bfb66e0ffaaea47f528674b4f0b25bfc9fc16430ceb355a330016ef1cc36148b46a1bc9060c386c5856fa27c0a164

test:
  secret_key_base: 9a4261888b666ee9a717a8198bf44ce89c2774406c0c16a7868e74c3eb93bc389b1ab51ba7318b319e11e379568cc0e5e456d0cb15af70da88569c6abbac5405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
